name: flutter_multi_dropdown
description: >
  A Flutter dropdown widget for single and multi select with search, checkboxes,
  radio buttons, select all support, and full UI customization.
version: 1.1.0
homepage: https://github.com/NamanGajera/flutter_multi_dropdown
topics:
  - dropdown
  - multi-select
  - single-select
  - flutter-widget
  - search

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

screenshots:
  - description: "Example screenshot 1"
    path: Images/custom_item_builder_dropdown.png
